--DROP TABLE students IF EXISTS;
CREATE TABLE students (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   surname VARCHAR(255),
   age INTEGER NOT NULL,
   email VARCHAR(255),
   specialisation VARCHAR(255),
   CONSTRAINT pk_students PRIMARY KEY (id)
);
CREATE TABLE teachers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   surname VARCHAR(255),
   age INTEGER NOT NULL,
   email VARCHAR(255),
   subject VARCHAR(255),
   CONSTRAINT pk_teachers PRIMARY KEY (id)
);
CREATE TABLE students_teachers (
  student_id INTEGER NOT NULL,
   teacher_id INTEGER NOT NULL
);

ALTER TABLE students_teachers ADD CONSTRAINT fk_stutea_on_student FOREIGN KEY (student_id) REFERENCES students (id);

ALTER TABLE students_teachers ADD CONSTRAINT fk_stutea_on_teacher FOREIGN KEY (teacher_id) REFERENCES teachers (id);